apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: retail-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      serviceAccountName: carts
      containers:
      - name: carts
        image: public.ecr.aws/aws-containers/retail-store-sample-cart:0.7.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: CARTS_DYNAMODB_TABLENAME
          value: "innovatemart-carts"
        - name: AWS_REGION
          value: "us-east-1"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 128m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: retail-store
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: carts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts
  namespace: retail-store
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::378388077304:role/innovatemart-eks-cluster-carts-dynamodb-role
