apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: retail-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: public.ecr.aws/aws-containers/retail-store-sample-catalog:0.7.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DB_ENDPOINT
          value: "innovatemart-catalog-mysql.coh82w20k2zy.us-east-1.rds.amazonaws.com"
        - name: DB_READ_ENDPOINT
          value: "innovatemart-catalog-mysql.coh82w20k2zy.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "catalog"
        - name: DB_USER
          value: "catalog_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-db-secrets
              key: mysql-password
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 128m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: retail-store
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: catalog
