apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: retail-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: public.ecr.aws/aws-containers/retail-store-sample-orders:0.7.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://orders-postgres:5432/orders
        - name: SPRING_DATASOURCE_USERNAME
          value: orders_user
        - name: SPRING_DATASOURCE_PASSWORD
          value: default_password
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 128m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: retail-store
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: orders
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-postgres
  namespace: retail-store
spec:
  serviceName: orders-postgres
  replicas: 1
  selector:
    matchLabels:
      app: orders-postgres
  template:
    metadata:
      labels:
        app: orders-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_DB
          value: orders
        - name: POSTGRES_USER
          value: orders_user
        - name: POSTGRES_PASSWORD
          value: default_password
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: orders-postgres
  namespace: retail-store
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: orders-postgres
