# .github/workflows/terraform.yml
name: 'Terraform Validation'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

env:
  TF_VERSION: 1.9.8

jobs:
  validate:
    name: 'Validate Terraform Configuration'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init (No Backend)
        id: init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Validation Success
        if: success()
        run: |
          echo "✅ Terraform configuration is valid!"
          echo "✅ All syntax checks passed!"
          echo "✅ Code is ready for manual deployment!"
